site_name: IronCore / cloud-hypervisor Provider
repo_url: https://github.com/ironcore-dev/cloud-hypervisor-provider/
edit_uri: edit/main/docs/
theme:
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.indexes
  - navigation.top
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  font:
    text: 'Work Sans'

plugins:
- search

markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.snippets
- codehilite
- admonition
- toc:
    permalink: true

nav:
- Home: README.md

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/ironcore-dev/cloud-hypervisor-provider
