version = 1
SPDX-PackageName = "cloud-hypervisor-provider"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/cloud-hypervisor-provider"

[[annotations]]
path = [
    ".github/**",
    "config/**",
    "go.mod",
    "go.sum",
    ".dockerignore",
    ".gitignore",
    ".golangci.yaml",
    "CODEOWNERS",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "Dockerfile",
    "Makefile",
    "mkdocs.yml",
    "hack/**.sh",
    "mkdocs.yml",
    "cloud-hypervisor/cloud-hypervisor.yaml",
    "cloud-hypervisor/client/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**",
    "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
